### ISSUE TITLE
Laravel socialite

### ISSUE THREAD

**Issue by Pok09** [wavezync/vue3-google-signin#44]
Hi!

I use laravel (socialite) as backend
I tried all the combinations suggested, but I always have the same error.

`Client error: GET https://www.googleapis.com/oauth2/v3/userinfo?prettyPrint=false resulted in a 401 Unauthorized response:\n{\n  \"error\": \"invalid_request\",\n  \"error_description\": \"Invalid Credentials\"\n}\n`

I used the same google client id for the backend and the front

Front (Nuxt)
```
const handleLoginSuccess = async (response: CredentialResponse) => {
  const { credential } = response
  await useFetch('/auth/social/google', {
    method: 'post',
    body: { token:  credential,  provider: 'google' }
  }).then((response) => {
    console.log(response.data.value)
  }).catch((error) => {
    console.log(error)
  }).finally(() => {
    loading.value = false
  })
}

```
Laravel socialite
`Socialite::driver($request->input('provider'))->stateless()->userFromToken($request->input('token'));`

Merci!!!

**Comment by kasvith** [comment]
@Pok09 can you provide full code in client side

**Comment by kasvith** [comment]
@Pok09 I checked the [source](https://github.com/laravel/socialite/blob/e9a18f0d477d0d25da133db819cc2738f5a06135/src/Two/GoogleProvider.php#L49C50-L49C95) of Laravel Socialite, and it seems they are using [Google OAuth2.0 API](https://developers.google.com/identity/protocols/oauth2)

To use that you may need a [custom button](https://vue3-google-signin.vercel.app/guide/creating-custom-buttons.html) that uses OAuth2.0

But if you still want to get the user from the token received from the `GoogleSignInButton` you can use the following [method](https://developers.google.com/identity/gsi/web/guides/verify-google-id-token#using-a-google-api-client-library)

**Comment by kasvith** [comment]
Let me know if it solves the issue

I thought to develop a more comprehensive guide for these kind of tasks

**Comment by Pok09** [comment]
Work perfect, With[ Creating Custom Buttons](https://vue3-google-signin.vercel.app/guide/creating-custom-buttons.html). 
**With useTokenClient**

```
<script setup lang="ts">
import {
  useTokenClient,
  type AuthCodeFlowSuccessResponse,
  type AuthCodeFlowErrorResponse,
} from "vue3-google-signin";

const handleOnSuccess = (response: AuthCodeFlowSuccessResponse) => {
  console.log("Access Token: ", response.access_token);
};

const handleOnError = (errorResponse: AuthCodeFlowErrorResponse) => {
  const result = await $fetch('/auth/social', {
    method: 'POST',
    body: JSON.stringify({
      token: response.access_token,
      provider: 'google'
    })
  })
};
....
</script>
```
`
$user = Socialite::driver($request->input('provider'))->stateless()->userFromToken($request->input('token'));`

**Comment by kasvith** [comment]
@Pok09 glad you made it
