### ISSUE TITLE
Google Loading GSI Error

### ISSUE THREAD

**Issue by artifex-pro** [wavezync/vue3-google-signin#45]
**Describe the bug**

Whenever loading the library it results into this given error:

GET https://accounts.google.com/gsi/client net::ERR_INVALID_HANDLE

var initialize = () => {
  isLoading.value = true;
  scriptTag = createScriptTag();
  document.head.appendChild(scriptTag);   ==>    Specifically fails here
  scriptTag.onload = () => {
    isLoading.value = false;
    loaded.value = true;
  };
  scriptTag.onerror = () => {
    isLoading.value = false;
    error.value = true;
  };
};

**To Reproduce**

On both nuxt-vue3-google-signin and vue3-google-signin it fails.

On firefox Nuxt 3 gets stuck because of the error.

On Google Chrome it's completely blocked.

**Comment by kasvith** [comment]
@artifex-pro can you provide a stackblitz or codesandbox? or a repo?

**Comment by kasvith** [comment]
This seems an issue from google's side
