### ISSUE TITLE
MS Authentication 

### ISSUE THREAD

**Issue by tguelcan** [wavezync/vue3-google-signin#52]
Thanks for your support to create for the possibility of authentication with google.

Could you imagine using another repo or this to extend **Microsoft Login**?

The background of my question is that many business applications, i.e. applications within companies in Europe rely on Microsoft products (Office365). Here it would be great if there was a simple way of authentication, similar to this repository.
This would also provide access to the development of "MS Teams" apps.
Is this already in planning?

**Comment by kasvith** [comment]
Hi, its not planned unfortunately

but we can consider doing that
