### ISSUE TITLE
One Tap still showing after login success

### ISSUE THREAD

**Issue by geofany** [wavezync/vue3-google-signin#58]
**Describe the bug**
hello i using one tap.
but after i success login.
The One Tap is still showing.
how to disabled it when user already logged in ?

**Comment by kasvith** [comment]
Hi @geofany would you provide us a stackblitz or codesandox?

**Comment by Pausejo** [comment]
This can ve achieved with a cookie, but I don't see that option in the composable

https://developers.google.com/identity/gsi/web/guides/toggle-display-with-cookies

Any roadmap on include this?

**Comment by kasvith** [comment]
im not sure JS API supports the cookie option

Kasun Vithanage

**Comment by Pausejo** [comment]
Ok, so then it's possible to achieve the same result this way: 

> const { isReady, login } = useOneTap({
> ...
> })
> 
> watch(isReady, (isReady) => {
>   if (!isReady) return
>   if (document.cookie.includes('my-cookie')) return
> 
>   login()
> })

**Comment by kasvith** [comment]
Yep sounds about right

Kasun Vithanage
