### ISSUE TITLE
Need token's iat and exp as part of DecodedGoogleUser

### ISSUE THREAD

**Issue by raevilman** [wavezync/vue3-google-signin#67]
**Is your feature request related to a problem? Please describe.**
Can we have JWT token's `iat` and `exp` fields as part of `DecodedGoogleUser`?

**Describe the solution you'd like**
If you are fine with having these two fields as part of the `DecodedGoogleUser`, I can send a PR for same.
Something like below:
```
export interface DecodedGoogleUser {
  email: string;
  email_verified: boolean;
  hd: string;
  family_name: string;
  given_name: string;
  name: string;
  id: string;
  picture: string;
  issued_at: number;
  expires_at: number;
}
```

**Comment by kasvith** [comment]
Sure, you can do a pr

**Comment by raevilman** [comment]
Done. #68

**Comment by kasvith** [comment]
thank you
