### ISSUE TITLE
ClientId may be undefined when using FedCM login

### ISSUE THREAD

**Issue by infinnie** [wavezync/vue3-google-signin#76]
**Describe the bug**
When using FedCM sign-in in Google Chrome, the `clientId` field passed to the callback may be `undefined`.

**To Reproduce**
Steps to reproduce the behaviour:
1. Log in to Google Chrome
2. Open a page that calls `useOneTap()` method to display Google’s OneTap sign in UI.
3. When clicking Continue as [[your name]], `onSuccess()` is not called, and `onError()` is called without arguments.

**Reproducible Example**
If you can please provide a reproducible example with [Stackbliz](https://stackblitz.com/), [CodeSandbox](https://codesandbox.io/) or any other suitable service

**Expected behaviour**

**Screenshots**

![image](https://github.com/wavezync/vue3-google-signin/assets/8168391/4b5427cd-9d20-487d-ab96-8b33ed5dcaee)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 125.0.6422.142

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kasvith** [comment]
Hi, i still didnt have time to check with FedCM

**Comment by kasvith** [comment]
related #74
