### ISSUE TITLE
vite reports an error when building with vue-tsc

### ISSUE THREAD

**Issue by xiaoai7904** [wavezync/vue3-google-signin#81]
<img width="1619" alt="image" src="https://github.com/user-attachments/assets/0ecae1e6-7c06-4875-a889-e1805fac4a7c">

"scripts": {
    "start": "vite",
    "build:pro": "vue-tsc -b && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@use-telegram-auth/client": "^1.0.5",
    "vue": "^3.4.31",
    "vue3-google-signin": "^1.3.5"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.0.5",
    "typescript": "^5.2.2",
    "vite": "^5.3.4",
    "vue-tsc": "^2.0.24"
  }
  
  pnpm run build:pro error

**Comment by kasvith** [comment]
interesting, can you provide a reproducible?

**Comment by kasvith** [comment]
hi @xiaoai7904 this should be fixed by #95
