### ISSUE TITLE
problem installing under quasar 2 vue 3 vite 

### ISSUE THREAD

**Issue by chiacy** [wavezync/vue3-google-signin#88]
failed to install under quasar 2 project, error as below

npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: vite-plugin-checker@0.7.2
npm error Found: vue-tsc@1.8.27
npm error node_modules/vue-tsc
npm error   vue-tsc@"^1.8.27" from vite-plugin-dts@3.9.1
npm error   node_modules/vite-plugin-dts
npm error     vite-plugin-dts@"^3.7.3" from vue3-google-signin@2.0.0
npm error     node_modules/vue3-google-signin
npm error       vue3-google-signin@"*" from the root project
npm error
npm error Could not resolve dependency:
npm error peerOptional vue-tsc@">=2.0.0" from vite-plugin-checker@0.7.2
npm error node_modules/vite-plugin-checker
npm error   dev vite-plugin-checker@"^0.7.1" from the root project
npm error
npm error Conflicting peer dependency: vue-tsc@2.1.6
npm error node_modules/vue-tsc
npm error   peerOptional vue-tsc@">=2.0.0" from vite-plugin-checker@0.7.2
npm error   node_modules/vite-plugin-checker
npm error     dev vite-plugin-checker@"^0.7.1" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.

**Comment by kasvith** [comment]
this should be fixed by https://github.com/wavezync/vue3-google-signin/releases/tag/v2.0.1

**Comment by chiacy** [comment]
Thanks!
